# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "同步证书"
  lane :sync_certs do |options|
    type = options[:type]
    if type.nil? || type == "all"
      match(type: "development", readonly: true)
      match(type: "appstore", readonly: true)
    elsif ['development', 'appstore'].include?(type)
      match(type: type, readonly: true)
    else
      UI.user_error!("type 参数必须是 'development', 'appstore' 或 'all' (默认 'all')")
    end
  end

  desc "生成/更新证书"
  lane :update_certs do |options|
    type = options[:type]
    UI.user_error!("type 参数必须是 'development' 或 'appstore'") unless ['development', 'appstore'].include?(type)
    match(type: type, readonly: false)
  end
end
